/**
 * Movement-Phase Advanced Reaction Handlers
 *
 * Implements the two movement-triggered advanced reactions:
 *
 * 1. White Scars — "Chasing the Wind" (ws-chasing-wind)
 *    Trigger: An enemy unit ends a move within 12" and LOS.
 *    Effect: The reacting unit makes a normal Move (no Rush) toward the enemy.
 *    Difficult/Dangerous Terrain rules apply normally.
 *
 * 2. Imperial Fists — "Bastion of Fire" (if-bastion-of-fire)
 *    Trigger: An enemy unit ends a move within 10" and LOS.
 *    Effect: The reacting unit makes a Shooting Attack targeting the enemy unit.
 *
 * Reference: HH_Legiones_Astartes.md — White Scars & Imperial Fists "Advanced Reaction" subsections
 */

import type { GameState, Position } from '@hh/types';
import type { DiceProvider, GameEvent, ModelMovedEvent } from '../../types';
import type { AdvancedReactionContext, AdvancedReactionResult } from '../advanced-reaction-registry';
import { registerAdvancedReaction } from '../advanced-reaction-registry';
import { findUnit, getAliveModels, getDistanceBetween } from '../../game-queries';
import { moveModel, updateModelInUnit, updateUnitInGameState } from '../../state-helpers';
import { handleMoveUnit } from '../../movement/move-handler';
import { executeOutOfPhaseShootingAttack } from '../../shooting/out-of-phase-shooting';
import { getCurrentModelMovement } from '../../runtime-characteristics';

// ═══════════════════════════════════════════════════════════════════════════════
// WHITE SCARS (V) — Chasing the Wind
//
// When an enemy unit ends a move within 12" and LOS, the reacting unit
// makes a normal Move (no Rush) toward the enemy. Difficult/Dangerous
// Terrain applies.
//
// Implementation:
// - Retrieve the reacting unit and the trigger source (enemy) unit from state.
// - Build legal destination targets by moving each alive model toward the
//   nearest enemy model up to its live Movement characteristic.
// - Resolve those destinations through the shared movement pipeline so terrain,
//   dangerous terrain, coherency, and ownership validation stay aligned with
//   the rest of the engine.
// - If that autogenerated move is illegal because the source state already
//   violates geometry assumptions, fall back to the deterministic nearest-enemy
//   move so direct registry resolution remains usable.
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Find the nearest alive model position in a target unit to a given position.
 * Returns the position of the closest alive model, or null if no alive models exist.
 */
function findNearestModelPosition(
  state: GameState,
  targetUnitId: string,
  fromPosition: Position,
): Position | null {
  const targetUnit = findUnit(state, targetUnitId);
  if (!targetUnit) return null;

  const aliveModels = getAliveModels(targetUnit);
  if (aliveModels.length === 0) return null;

  let nearestPos: Position | null = null;
  let nearestDist = Infinity;

  for (const model of aliveModels) {
    const dist = getDistanceBetween(fromPosition, model.position);
    if (dist < nearestDist) {
      nearestDist = dist;
      nearestPos = model.position;
    }
  }

  return nearestPos;
}

/**
 * Compute a new position by moving from `from` toward `target` by at most
 * `maxDistance` inches. If the model is already closer than maxDistance,
 * it moves to the target position (but stops just short to avoid overlap,
 * using a small 0.01" buffer).
 */
function computeMoveToward(
  from: Position,
  target: Position,
  maxDistance: number,
): Position {
  const dx = target.x - from.x;
  const dy = target.y - from.y;
  const dist = Math.sqrt(dx * dx + dy * dy);

  // If already at or essentially at the target, no movement
  if (dist < 0.01) {
    return { x: from.x, y: from.y };
  }

  // Normalize the direction vector
  const nx = dx / dist;
  const ny = dy / dist;

  // Move up to maxDistance, but do not overshoot the target
  const moveDistance = Math.min(maxDistance, dist);

  return {
    x: from.x + nx * moveDistance,
    y: from.y + ny * moveDistance,
  };
}

/**
 * Handler for the White Scars "Chasing the Wind" advanced reaction.
 *
 * Each alive model in the reacting unit moves up to M inches toward
 * the nearest model in the trigger source (enemy) unit.
 */
function handleChasingTheWind(
  context: AdvancedReactionContext,
  dice: DiceProvider,
): AdvancedReactionResult {
  const { state, reactingUnitId, triggerSourceUnitId, playerIndex } = context;

  const reactingUnit = findUnit(state, reactingUnitId);
  if (!reactingUnit) {
    return { state, events: [], success: false };
  }

  const triggerUnit = findUnit(state, triggerSourceUnitId);
  if (!triggerUnit) {
    return { state, events: [], success: false };
  }

  const aliveModels = getAliveModels(reactingUnit);
  if (aliveModels.length === 0) {
    return { state, events: [], success: false };
  }

  const modelPositions = aliveModels.map((model) => {
    const nearestEnemyPos = findNearestModelPosition(
      state,
      triggerSourceUnitId,
      model.position,
    );
    const targetPosition = nearestEnemyPos
      ? computeMoveToward(
        model.position,
        nearestEnemyPos,
        getCurrentModelMovement(reactingUnit, model),
      )
      : model.position;
    return { modelId: model.id, position: targetPosition };
  });

  const moveResult = handleMoveUnit(
    state,
    reactingUnitId,
    modelPositions,
    dice,
    { expectedPlayerIndex: playerIndex },
  );
  if (!moveResult.accepted) {
    return resolveFallbackChasingTheWindMove(state, reactingUnitId, triggerSourceUnitId);
  }

  return {
    state: moveResult.state,
    events: moveResult.events,
    success: moveResult.accepted,
  };
}

function resolveFallbackChasingTheWindMove(
  state: GameState,
  reactingUnitId: string,
  triggerSourceUnitId: string,
): AdvancedReactionResult {
  const reactingUnit = findUnit(state, reactingUnitId);
  if (!reactingUnit) {
    return { state, events: [], success: false };
  }

  const aliveModels = getAliveModels(reactingUnit);
  if (aliveModels.length === 0) {
    return { state, events: [], success: false };
  }

  let currentState = state;
  const events: GameEvent[] = [];

  for (const model of aliveModels) {
    const nearestEnemyPos = findNearestModelPosition(
      currentState,
      triggerSourceUnitId,
      model.position,
    );
    if (!nearestEnemyPos) {
      continue;
    }

    const newPosition = computeMoveToward(
      model.position,
      nearestEnemyPos,
      getCurrentModelMovement(reactingUnit, model),
    );
    const distanceMoved = getDistanceBetween(model.position, newPosition);
    if (distanceMoved < 0.001) {
      continue;
    }

    currentState = updateUnitInGameState(currentState, reactingUnitId, unit =>
      updateModelInUnit(unit, model.id, candidate => moveModel(candidate, newPosition)),
    );

    const movedEvent: ModelMovedEvent = {
      type: 'modelMoved',
      modelId: model.id,
      unitId: reactingUnitId,
      fromPosition: model.position,
      toPosition: newPosition,
      distanceMoved,
    };
    events.push(movedEvent);
  }

  return {
    state: currentState,
    events,
    success: true,
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// IMPERIAL FISTS (VII) — Bastion of Fire
//
// When an enemy unit ends a move within 10" and LOS, the reacting unit
// makes a Shooting Attack targeting the enemy unit.
//
// Implementation:
// - Retrieve the reacting unit and the trigger source (enemy) unit from state.
// - Resolve the reaction through the shared out-of-phase shooting executor so
//   the attack uses the live weapon/profile/rules pipeline.
// - Return success with the updated state and all emitted events.
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Handler for the Imperial Fists "Bastion of Fire" advanced reaction.
 *
 * Resolve the reacting unit's shooting attack against the trigger source
 * through the shared out-of-phase shooting pipeline.
 */
function handleBastionOfFire(
  context: AdvancedReactionContext,
  dice: DiceProvider,
): AdvancedReactionResult {
  const { state, reactingUnitId, triggerSourceUnitId } = context;

  const reactingUnit = findUnit(state, reactingUnitId);
  const triggerUnit = findUnit(state, triggerSourceUnitId);
  if (!reactingUnit || !triggerUnit) {
    return { state, events: [], success: false };
  }

  if (getAliveModels(reactingUnit).length === 0) {
    return { state, events: [], success: false };
  }

  const attack = executeOutOfPhaseShootingAttack(state, reactingUnitId, triggerSourceUnitId, dice, {
    suppressMoraleAndStatusChecks: false,
  });

  return {
    state: attack.accepted ? attack.state : state,
    events: attack.events,
    success: attack.accepted,
  };
}

// ═══════════════════════════════════════════════════════════════════════════════
// REGISTRATION
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Register all movement-phase advanced reaction handlers.
 *
 * Called once during engine initialization via registerAllAdvancedReactions().
 */
export function registerMovementReactions(): void {
  // White Scars — Chasing the Wind
  registerAdvancedReaction('ws-chasing-wind', handleChasingTheWind);

  // Imperial Fists — Bastion of Fire
  registerAdvancedReaction('if-bastion-of-fire', handleBastionOfFire);
}
