/**
 * Special Rules Registry
 * Maps rule names to handler functions for movement phase processing.
 * Reference: HH_Armoury.md — Movement special rules
 */

import type { GameState, UnitState } from '@hh/types';
import type { DiceProvider, GameEvent, ValidationError } from '../types';

// ─── Movement Rule Handler Interface ─────────────────────────────────────────

/**
 * Context passed to movement rule handlers.
 */
export interface MovementRuleContext {
  state: GameState;
  unit: UnitState;
  dice: DiceProvider;
  terrain: GameState['terrain'];
  battlefieldWidth: number;
  battlefieldHeight: number;
}

/**
 * Result of applying a movement rule.
 */
export interface MovementRuleResult {
  /** Modified movement distance (if the rule changes it) */
  modifiedMovement?: number;
  /** Whether the unit counts as stationary after moving */
  countsAsStationary?: boolean;
  /** Whether the unit ignores difficult terrain */
  ignoresDifficultTerrain?: boolean;
  /** Whether the unit ignores dangerous terrain */
  ignoresDangerousTerrain?: boolean;
  /** Whether the unit can re-roll rush distance */
  canRerollRush?: boolean;
  /** Additional movement bonus */
  movementBonus?: number;
  /** Whether deep strike entry is allowed */
  allowsDeepStrike?: boolean;
  /** Whether outflank entry is allowed */
  allowsOutflank?: boolean;
  /** Whether the unit can charge after disembarking (Assault Vehicle) */
  canChargeAfterDisembark?: boolean;
  /** Transport capacity modifier (Bulky X) */
  bulkyValue?: number;
  /** Events generated by the rule */
  events?: GameEvent[];
  /** Validation errors generated by the rule */
  errors?: ValidationError[];
}

/**
 * A movement rule handler function.
 */
export type MovementRuleHandler = (
  context: MovementRuleContext,
  ruleValue?: string | number,
) => MovementRuleResult;

// ─── Registry ────────────────────────────────────────────────────────────────

const movementRuleRegistry = new Map<string, MovementRuleHandler>();

/**
 * Register a movement rule handler.
 */
export function registerMovementRule(name: string, handler: MovementRuleHandler): void {
  movementRuleRegistry.set(name.toLowerCase(), handler);
}

/**
 * Get a movement rule handler by name.
 */
export function getMovementRule(name: string): MovementRuleHandler | undefined {
  return movementRuleRegistry.get(name.toLowerCase());
}

/**
 * Check if a movement rule is registered.
 */
export function hasMovementRule(name: string): boolean {
  return movementRuleRegistry.has(name.toLowerCase());
}

/**
 * Get all registered rule names.
 */
export function getRegisteredRuleNames(): string[] {
  return Array.from(movementRuleRegistry.keys());
}

/**
 * Clear all registered rules (for testing).
 */
export function clearRegistry(): void {
  movementRuleRegistry.clear();
}

/**
 * Apply all applicable movement rules for a unit.
 * Merges the results from all matching rules.
 *
 * @param ruleNames - Array of rule names (with optional values) to apply
 * @param context - The movement rule context
 * @returns Merged result of all applied rules
 */
export function applyMovementRules(
  ruleNames: Array<{ name: string; value?: string | number }>,
  context: MovementRuleContext,
): MovementRuleResult {
  const merged: MovementRuleResult = {
    events: [],
    errors: [],
  };

  for (const { name, value } of ruleNames) {
    const handler = getMovementRule(name);
    if (!handler) continue;

    const result = handler(context, value);

    // Merge results — later rules override earlier ones for scalar values
    if (result.modifiedMovement !== undefined) {
      merged.modifiedMovement = result.modifiedMovement;
    }
    if (result.countsAsStationary) {
      merged.countsAsStationary = true;
    }
    if (result.ignoresDifficultTerrain) {
      merged.ignoresDifficultTerrain = true;
    }
    if (result.ignoresDangerousTerrain) {
      merged.ignoresDangerousTerrain = true;
    }
    if (result.canRerollRush) {
      merged.canRerollRush = true;
    }
    if (result.movementBonus !== undefined) {
      merged.movementBonus = (merged.movementBonus ?? 0) + result.movementBonus;
    }
    if (result.allowsDeepStrike) {
      merged.allowsDeepStrike = true;
    }
    if (result.allowsOutflank) {
      merged.allowsOutflank = true;
    }
    if (result.canChargeAfterDisembark) {
      merged.canChargeAfterDisembark = true;
    }
    if (result.bulkyValue !== undefined) {
      merged.bulkyValue = result.bulkyValue;
    }
    if (result.events) {
      merged.events!.push(...result.events);
    }
    if (result.errors) {
      merged.errors!.push(...result.errors);
    }
  }

  return merged;
}
