/**
 * Return Fire Reaction Handler
 * Implements the Return Fire reaction during the Shooting Phase.
 *
 * Reference: HH_Rules_Battle.md -- "Return Fire Reaction"
 * Reference: HH_Principles.md -- "Reaction Allotments, Core Reactions"
 *
 * Return Fire flow:
 * 1. Active player's shooting attack resolves wounds/saves (before Step 11 casualty removal).
 * 2. The reactive player may choose one eligible unit to Return Fire at the attacking unit.
 * 3. Uses the existing reaction allotment system (army.reactionAllotmentRemaining > 0).
 * 4. The reacting unit fires a full shooting attack back, with restrictions:
 *    a. Must have LOS to the attacker (no Barrage ignoring LOS).
 *    b. Vehicles: only Defensive Weapons (S <= 6 or trait-designated).
 *    c. Reacting unit counts as Stationary for snap shot purposes.
 *    d. No morale checks generated by Return Fire.
 *    e. No status application from Return Fire hits/wounds.
 *    f. Return Fire does not consume the reacting unit's future shooting action.
 *    g. The reacting unit is marked as hasReactedThisTurn.
 *
 * Trigger conditions:
 * - Reactive player has reactionAllotmentRemaining > 0
 * - Target unit (that was shot at) can react: not already reacted, not Stunned,
 *   not Routed, not locked in combat, deployed, not embarked
 * - The target unit itself is eligible to Return Fire
 */

import type {
  GameState,
  UnitState,
} from '@hh/types';
import type { GameEvent, ReturnFireTriggeredEvent } from '../types';
import {
  findUnit,
  findUnitArmy,
  findUnitPlayerIndex,
  canUnitReact,
  hasReactionAllotment,
  getAliveModels,
  isVehicleUnit,
} from '../game-queries';
import {
  updateUnitInGameState,
  updateArmyByIndex,
} from '../state-helpers';

// ---- Result Types ----------------------------------------------------------

/**
 * Result of checking for Return Fire trigger.
 */
export interface ReturnFireCheckResult {
  /** Whether Return Fire can be triggered */
  canReturnFire: boolean;
  /** Unit IDs eligible to Return Fire */
  eligibleUnitIds: string[];
  /** Events emitted */
  events: GameEvent[];
}

/**
 * Result of executing a Return Fire reaction.
 */
export interface ReturnFireExecutionResult {
  /** Updated game state after Return Fire */
  state: GameState;
  /** Events emitted during Return Fire */
  events: GameEvent[];
}

/**
 * Restrictions that apply to a Return Fire action.
 */
export interface ReturnFireRestrictions {
  /** Whether the unit counts as stationary (always true for Return Fire) */
  countsAsStationary: boolean;
  /** Whether only defensive weapons can fire (true for vehicles) */
  defensiveWeaponsOnly: boolean;
  /** Whether this is a Return Fire action (for pipeline to skip morale/status) */
  isReturnFire: boolean;
  /** Whether Barrage weapons can ignore LOS (always false for Return Fire) */
  canIgnoreLOS: boolean;
}

// ---- checkReturnFireTrigger ------------------------------------------------

/**
 * Check if Return Fire can be triggered after a shooting attack.
 *
 * After the active player's shooting attack resolves wounds/saves (before
 * Step 11 casualty removal), the reactive player may choose one eligible
 * unit to Return Fire at the attacking unit.
 *
 * The check verifies:
 * 1. The target unit exists and has alive models.
 * 2. The attacker unit exists and has alive models.
 * 3. The target unit's army (reactive player) has reaction allotments remaining.
 * 4. The target unit passes the canUnitReact eligibility check.
 *
 * @param state - Current game state
 * @param targetUnitId - Unit that was shot at (potential Return Fire unit)
 * @param attackerUnitId - Unit that did the shooting (Return Fire target)
 * @returns Whether Return Fire is possible and which units are eligible
 */
export function checkReturnFireTrigger(
  state: GameState,
  targetUnitId: string,
  attackerUnitId: string,
): ReturnFireCheckResult {
  const noTrigger: ReturnFireCheckResult = {
    canReturnFire: false,
    eligibleUnitIds: [],
    events: [],
  };

  // Find the target unit (the one that was shot at and could Return Fire)
  const targetUnit = findUnit(state, targetUnitId);
  if (!targetUnit) {
    return noTrigger;
  }

  // Target unit must have alive models to fire back
  const targetAliveModels = getAliveModels(targetUnit);
  if (targetAliveModels.length === 0) {
    return noTrigger;
  }

  // Find the attacker unit (the one that will be the Return Fire target)
  const attackerUnit = findUnit(state, attackerUnitId);
  if (!attackerUnit) {
    return noTrigger;
  }

  // Attacker unit must have alive models to be a valid target
  const attackerAliveModels = getAliveModels(attackerUnit);
  if (attackerAliveModels.length === 0) {
    return noTrigger;
  }

  // Find the army the target unit belongs to (the reactive player's army)
  const targetArmy = findUnitArmy(state, targetUnitId);
  if (!targetArmy) {
    return noTrigger;
  }

  // Check that the reactive player has reaction allotments remaining
  if (!hasReactionAllotment(targetArmy)) {
    return noTrigger;
  }

  // Check that the target unit is eligible to react
  if (!canUnitReact(targetUnit)) {
    return noTrigger;
  }

  // Target unit is eligible to Return Fire
  const eligibleUnitIds = [targetUnitId];

  // Emit the ReturnFireTriggeredEvent
  const triggerEvent: ReturnFireTriggeredEvent = {
    type: 'returnFireTriggered',
    targetUnitId: attackerUnitId,
    eligibleUnitIds,
  };

  return {
    canReturnFire: true,
    eligibleUnitIds,
    events: [triggerEvent],
  };
}

// ---- isDefensiveWeapon -----------------------------------------------------

/**
 * Check if a weapon qualifies as a Defensive Weapon.
 * Defensive weapons have Strength 6 or less, or have the "Defensive" trait.
 * Used for vehicle Return Fire restrictions -- vehicles can only fire
 * Defensive Weapons during a Return Fire reaction.
 *
 * Reference: HH_Rules_Battle.md -- "Defensive Weapons"
 *
 * @param weaponStrength - The weapon's strength value
 * @param weaponTraits - The weapon's traits array
 * @returns Whether this weapon qualifies as a defensive weapon
 */
export function isDefensiveWeapon(
  weaponStrength: number,
  weaponTraits: string[],
): boolean {
  // Check if the weapon has the "Defensive" trait (case-insensitive)
  const hasDefensiveTrait = weaponTraits.some(
    (trait) => trait.toLowerCase() === 'defensive',
  );
  if (hasDefensiveTrait) {
    return true;
  }

  // Defensive weapons have Strength 6 or less
  return weaponStrength <= 6;
}

// ---- markUnitReacted -------------------------------------------------------

/**
 * Mark a unit as having reacted this turn and decrement the owning army's
 * reaction allotment.
 *
 * This is called after a Return Fire reaction is executed:
 * - Sets the unit's hasReactedThisTurn to true
 * - Decrements the army's reactionAllotmentRemaining by 1
 *
 * @param state - Current game state
 * @param unitId - Unit that reacted
 * @returns Updated game state with the unit marked and allotment decremented
 */
export function markUnitReacted(
  state: GameState,
  unitId: string,
): GameState {
  // Find which player index the unit belongs to
  const playerIndex = findUnitPlayerIndex(state, unitId);
  if (playerIndex === undefined) {
    return state;
  }

  // Mark the unit as having reacted this turn
  let newState = updateUnitInGameState(state, unitId, (unit) => ({
    ...unit,
    hasReactedThisTurn: true,
  }));

  // Decrement the army's reaction allotment remaining
  newState = updateArmyByIndex(newState, playerIndex, (army) => ({
    ...army,
    reactionAllotmentRemaining: Math.max(0, army.reactionAllotmentRemaining - 1),
  }));

  return newState;
}

// ---- getReturnFireRestrictions ---------------------------------------------

/**
 * Get Return Fire restrictions for a unit.
 * Returns information about what constraints apply to a Return Fire action.
 *
 * Restrictions:
 * - The unit always counts as Stationary for snap shot purposes (even if it
 *   moved earlier in the turn). This means Heavy weapons do NOT fire as snap
 *   shots during Return Fire.
 * - Vehicles can only fire Defensive Weapons (S <= 6 or Defensive trait).
 * - This is a Return Fire action, so the pipeline should skip morale checks
 *   and status application from hits/wounds.
 * - Barrage weapons cannot ignore LOS during Return Fire.
 *
 * @param unit - The unit attempting Return Fire
 * @returns Restrictions object describing what constraints apply
 */
export function getReturnFireRestrictions(
  unit: UnitState,
): ReturnFireRestrictions {
  const isVehicle = isVehicleUnit(unit);

  return {
    countsAsStationary: true,
    defensiveWeaponsOnly: isVehicle,
    isReturnFire: true,
    canIgnoreLOS: false,
  };
}
