/**
 * AI Opponent Types
 *
 * Core type definitions for the AI strategy system.
 * The AI is stateless per-call but uses an AITurnContext to track
 * which units have already acted within the current sub-phase.
 */

import type { GameState, GameCommand, Position } from '@hh/types';
import { Phase, SubPhase } from '@hh/types';
import type { DeploymentFormationPreset } from '@hh/geometry';

// ─── Strategy Tier ───────────────────────────────────────────────────────────

/**
 * AI strategy tier. Determines the sophistication of decision-making.
 */
export enum AIStrategyTier {
  /** Random valid actions — no tactical intelligence */
  Basic = 'Basic',
  /** Heuristic-based tactical decisions */
  Tactical = 'Tactical',
  /** Search + NNUE engine */
  Engine = 'Engine',
  /** Transformer policy/value + PUCT/MCTS search */
  Alpha = 'Alpha',
}

// ─── Configuration ───────────────────────────────────────────────────────────

export interface ShadowAlphaConfig {
  /** Whether Alpha shadow mode is enabled for this seat. */
  enabled: boolean;
  /** Alpha model ID to use for shadow inference. */
  alphaModelId?: string;
  /** Search budget in ms for Alpha shadow inference. */
  timeBudgetMs?: number;
  /** Optional hard cap on Alpha simulations. */
  maxSimulations?: number;
  /** Deterministic base seed for Alpha shadow sampling. */
  baseSeed?: number;
  /** Emit Alpha shadow diagnostics. */
  diagnosticsEnabled?: boolean;
}

/**
 * Configuration for an AI player.
 */
export interface AIPlayerConfig {
  /** Which player index this AI controls (0 or 1) */
  playerIndex: number;
  /** Strategy tier to use */
  strategyTier: AIStrategyTier;
  /** Preferred deployment formation when placing units before the game */
  deploymentFormation: AIDeploymentFormation;
  /** Delay between commands in ms (for UI pacing, 0 = instant) */
  commandDelayMs: number;
  /** Search time budget for the Engine tier. */
  timeBudgetMs?: number;
  /** Gameplay NNUE model ID to use for the Engine tier. */
  nnueModelId?: string;
  /** Alpha transformer model ID to use for the Alpha tier. */
  alphaModelId?: string;
  /** Deterministic base seed used by Engine search sampling. */
  baseSeed?: number;
  /** Number of deterministic rollout samples to average per searched action. */
  rolloutCount?: number;
  /** Soft maximum iterative-deepening depth for the Engine tier. */
  maxDepthSoft?: number;
  /** Hard simulation cap used by the Alpha tier. */
  maxSimulations?: number;
  /** Emit per-decision diagnostics for observers and the UI. */
  diagnosticsEnabled?: boolean;
  /** Optional Alpha shadow-mode sidecar for non-Alpha live seats. */
  shadowAlpha?: ShadowAlphaConfig | null;
  /** Whether the AI is enabled */
  enabled: boolean;
}

export type AIDeploymentFormation = 'auto' | DeploymentFormationPreset;

// ─── Turn Context ────────────────────────────────────────────────────────────

/**
 * Mutable context that persists across generateNextCommand calls within
 * a single sub-phase. Reset automatically when the phase/sub-phase changes.
 *
 * This solves the problem of a stateless AI needing to remember which
 * units it has already issued commands for (since the engine doesn't
 * track per-turn shooting usage, etc.).
 */
export interface AITurnContext {
  /** Unit IDs that have already been issued commands in the current sub-phase */
  actedUnitIds: Set<string>;
  /** Model IDs that have already been moved in the current move command sequence */
  movedModelIds: Set<string>;
  /** The unit currently being processed (for multi-model movement) */
  currentMovingUnitId: string | null;
  /** Phase when this context was last used */
  lastPhase: Phase | null;
  /** Sub-phase when this context was last used */
  lastSubPhase: SubPhase | null;
  /** Root-state fingerprint expected before the next queued command. */
  latestStateFingerprint: string | null;
  /** Decision owner (active or reactive player) from the last invocation. */
  lastDecisionOwner: number | null;
  /** Commands already planned by search and ready to emit on subsequent calls. */
  queuedPlan: QueuedCommandStep[];
  /** Fingerprint of the state in which the most recent command was issued. */
  pendingResultFingerprint: string | null;
  /** Decision owner for the most recent emitted command. */
  pendingResultDecisionOwner: number | null;
  /** Command type for the most recent emitted command. */
  pendingResultCommandType: GameCommand['type'] | null;
  /** Most recent diagnostics generated by the AI layer. */
  latestDiagnostics: AIDiagnostics | null;
  /** Most recent hard error generated by the AI layer. */
  latestError: string | null;
  /** Last completed root score from the Engine tier. */
  lastEngineScore: number | null;
}

// ─── Strategy Interface ──────────────────────────────────────────────────────

/**
 * The core AI strategy interface. Both Basic and Tactical implement this.
 */
export interface AIStrategy {
  /**
   * Generate the next command for the AI player to execute.
   * Returns null if no action is available (end of sub-phase, etc.).
   */
  generateNextCommand(
    state: GameState,
    playerIndex: number,
    context: AITurnContext,
  ): GameCommand | null;

  /**
   * Generate a deployment command for placing units during pre-game.
   * Returns null if deployment is complete.
   */
  generateDeploymentCommand(
    state: GameState,
    playerIndex: number,
    deployedUnitIds: string[],
    deploymentZoneDepth: number,
    deploymentFormation: AIDeploymentFormation,
  ): DeploymentCommand | null;
}

// ─── Deployment ──────────────────────────────────────────────────────────────

/**
 * Result from deployment AI — a unit to deploy with its model positions.
 */
export interface DeploymentCommand {
  unitId: string;
  modelPositions: { modelId: string; position: Position }[];
}

// ─── Engine Search + NNUE ───────────────────────────────────────────────────

export interface QueuedCommandStep {
  command: GameCommand;
  expectedStateFingerprint: string;
  decisionOwner: number;
  phase: Phase;
  subPhase: SubPhase;
  label: string;
}

export interface MacroAction {
  id: string;
  label: string;
  commands: GameCommand[];
  orderingScore: number;
  actorIds: string[];
  reasons: string[];
}

export interface AlphaDiagnosticSummary {
  tier: AIStrategyTier.Alpha;
  modelId?: string;
  selectedMacroActionId?: string;
  selectedMacroActionLabel?: string;
  selectedCommandType?: GameCommand['type'];
  valueEstimate?: number;
  rootVisits?: number;
  nodesExpanded?: number;
  policyEntropy?: number;
  searchTimeMs?: number;
  principalVariation: string[];
  error?: string;
}

export interface AIDiagnostics {
  tier: AIStrategyTier;
  modelId?: string;
  selectedMacroActionId?: string;
  selectedMacroActionLabel?: string;
  selectedCommandType?: GameCommand['type'];
  shadowAlphaDiagnostics?: AlphaDiagnosticSummary;
  searchTimeMs?: number;
  score?: number;
  depthCompleted?: number;
  nodesVisited?: number;
  rolloutCount?: number;
  principalVariation: string[];
  error?: string;
}

export interface AlphaAIDiagnostics extends AIDiagnostics {
  tier: AIStrategyTier.Alpha;
  valueEstimate?: number;
  rootVisits?: number;
  nodesExpanded?: number;
  policyEntropy?: number;
}

export interface SearchConfig {
  timeBudgetMs: number;
  nnueModelId: string;
  baseSeed: number;
  rolloutCount: number;
  maxDepthSoft: number;
  diagnosticsEnabled: boolean;
  maxRootActions: number;
  maxActionsPerUnit: number;
  aspirationWindow: number;
  maxAutoAdvanceSteps: number;
}

export interface SearchResult {
  bestAction: MacroAction | null;
  score: number;
  depthCompleted: number;
  nodesVisited: number;
  searchTimeMs: number;
  principalVariation: string[];
  diagnostics: AIDiagnostics;
  queuedPlan: QueuedCommandStep[];
}

export type AlphaStateTokenType = 'global' | 'unit' | 'objective' | 'terrain' | 'context';

export interface AlphaEncodedStateToken {
  tokenType: AlphaStateTokenType;
  stableId: string;
  position: Position | null;
  features: number[];
}

export interface AlphaEncodedAction {
  macroActionId: string;
  label: string;
  actorIds: string[];
  targetIds: string[];
  features: number[];
}

export interface AlphaTransformerHyperparameters {
  stateFeatureDimension: number;
  actionFeatureDimension: number;
  coordinateFeatureDimension: number;
  tokenTypeCount: number;
  modelWidth: number;
  layerCount: number;
  attentionHeads: number;
  feedForwardWidth: number;
  dropoutRate: number;
  maxStateTokens: number;
  maxActionTokens: number;
}

export interface AlphaTrainingMetadata {
  trainedAt: string;
  datasetName: string;
  datasetSize: number;
  epochs: number;
  optimizer: string;
  learningRate: number;
  teacherModelId?: string | null;
  selfPlayGames?: number;
  notes?: string;
}

export interface SerializedAlphaTensor {
  shape: number[];
  dataBase64: string;
}

export interface SerializedAlphaModelManifest {
  modelFamily: 'alpha-transformer';
  schemaVersion: number;
  tokenSchemaVersion: number;
  actionSchemaVersion: number;
  modelId: string;
  weightsChecksum: string;
  trainingMetadata: AlphaTrainingMetadata;
  hyperparameters: AlphaTransformerHyperparameters;
  tokenSortingRules: string[];
  tokenTruncationRules: string[];
}

export interface SerializedAlphaModel {
  manifest: SerializedAlphaModelManifest;
  tensors: Record<string, SerializedAlphaTensor>;
}

export interface AlphaTensor {
  shape: number[];
  data: Float32Array;
}

export interface AlphaModel {
  manifest: SerializedAlphaModelManifest;
  tensors: Record<string, AlphaTensor>;
}

export interface AlphaSearchConfig {
  timeBudgetMs: number;
  maxSimulations: number;
  alphaModelId: string;
  baseSeed: number;
  diagnosticsEnabled: boolean;
  batchSize: number;
  maxRootActions: number;
  maxActionsPerUnit: number;
  maxAutoAdvanceSteps: number;
  puctExploration: number;
  dirichletAlpha: number;
  dirichletEpsilon: number;
  policyPriorBlend: number;
  valueBlend: number;
  rootTemperature: number;
  reuseRoots: boolean;
}

export interface AlphaSearchResult {
  bestAction: MacroAction | null;
  valueEstimate: number;
  rootVisits: number;
  nodesExpanded: number;
  searchTimeMs: number;
  policyEntropy: number;
  principalVariation: string[];
  diagnostics: AlphaAIDiagnostics;
  queuedPlan: QueuedCommandStep[];
}

export interface AlphaReplayBufferEntry {
  state: GameState;
  rootPlayerIndex: number;
  actions: MacroAction[];
  policyTarget: number[];
  valueTarget: number;
  vpDeltaTarget: number;
  tacticalSwingTarget: number;
  source: 'distill' | 'selfplay' | 'shadow';
  sourceModelId?: string;
  sourceMatchId?: string;
  sourceStep?: number;
}

export interface QuantizedLayer {
  inputSize: number;
  outputSize: number;
  weightScale: number;
  biasScale: number;
  weights: Int8Array;
  biases: Int16Array;
}

export interface NNUEModelManifest {
  modelId: string;
  modelKind: 'gameplay' | 'roster';
  schemaVersion: number;
  featureVersion: number;
  weightsChecksum: string;
}

export interface NNUEModel {
  manifest: NNUEModelManifest;
  inputSize: number;
  hiddenLayer: QuantizedLayer;
  outputLayer: QuantizedLayer;
}

export interface SerializedNNUEModel {
  manifest: NNUEModelManifest;
  inputSize: number;
  hiddenLayer: {
    inputSize: number;
    outputSize: number;
    weightScale: number;
    biasScale: number;
    weights: number[];
    biases: number[];
  };
  outputLayer: {
    inputSize: number;
    outputSize: number;
    weightScale: number;
    biasScale: number;
    weights: number[];
    biases: number[];
  };
}

export interface Evaluator {
  readonly model: NNUEModel;
  evaluate(state: GameState, playerIndex: number): number;
}

// ─── Scoring ─────────────────────────────────────────────────────────────────

/**
 * Scoring data for a potential target. Used by Tactical strategy.
 */
export interface TargetScore {
  unitId: string;
  score: number;
  reasons: string[];
}

/**
 * Movement evaluation for a potential destination.
 */
export interface MovementScore {
  position: Position;
  score: number;
  reasons: string[];
}

/**
 * Strategy tier string literal type used by phase handlers.
 * Matches the lowercase version of AIStrategyTier values.
 */
export type StrategyMode = 'basic' | 'tactical';
