import path from 'node:path';

export const DEFAULT_ALPHA_MODEL_OVERRIDE_FILE = path.join(
  'packages',
  'ai',
  'src',
  'alpha',
  'default-alpha-model-override.ts',
);

export const DEFAULT_ALPHA_PROMOTION_ARCHIVE_ROOT = path.join(
  'archive',
  'alpha',
  'promotions',
);

export const DEFAULT_ALPHA_PROMOTION_ARCHIVE_INDEX_FILE = path.join(
  DEFAULT_ALPHA_PROMOTION_ARCHIVE_ROOT,
  'index.json',
);

function sanitizeArchiveSegment(value) {
  return String(value)
    .trim()
    .replace(/[^a-zA-Z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    || 'promotion';
}

export function createAlphaPromotionArchiveDirName(sourceModelId, promotedAt) {
  const normalizedTimestamp = promotedAt.replace(/[:.]/g, '-');
  return `${normalizedTimestamp}-${sanitizeArchiveSegment(sourceModelId)}`;
}

export function buildPromotedAlphaSerializedModel(serializedModel, defaultModelId) {
  return {
    ...serializedModel,
    manifest: {
      ...serializedModel.manifest,
      modelId: defaultModelId,
    },
  };
}

export function normalizeAlphaPromotionGateResult(gateSummary, expectedModelId, force = false) {
  if (!gateSummary) {
    if (force) return null;
    throw new Error('Promotion requires --gate-summary unless --force is provided.');
  }

  if (gateSummary.candidateModelId !== expectedModelId) {
    throw new Error(
      `Gate summary candidate "${gateSummary.candidateModelId}" does not match model "${expectedModelId}".`,
    );
  }

  const threshold = Number(gateSummary.threshold ?? 0);
  const winRate = Number(gateSummary.winRate ?? 0);
  const passed = typeof gateSummary.passed === 'boolean'
    ? gateSummary.passed
    : winRate > threshold;

  if (!passed && !force) {
    throw new Error('Gate summary did not pass. Re-run with --force if you intentionally want to bypass gate failure.');
  }

  return {
    passed,
    winRate,
    candidateWins: Number(gateSummary.candidateWins ?? 0),
    engineWins: Number(gateSummary.engineWins ?? 0),
    tacticalWins: Number(gateSummary.tacticalWins ?? 0),
    defaultAlphaWins: Number(gateSummary.defaultAlphaWins ?? 0),
    draws: Number(gateSummary.draws ?? 0),
    aborted: Number(gateSummary.aborted ?? 0),
    timeouts: Number(gateSummary.timeouts ?? 0),
    threshold,
    timeBudgetMs: Number(gateSummary.timeBudgetMs ?? 0),
    maxSimulations: Number(gateSummary.maxSimulations ?? 0),
    matchesPerOpponent: Number(gateSummary.matchesPerOpponent ?? 0),
  };
}

export function renderDefaultAlphaOverrideModule(serializedModel, metadata) {
  return `import type { SerializedAlphaModel } from '../types';

export interface DefaultAlphaModelOverrideMetadata {
  sourceModelId: string;
  sourceModelPath: string;
  gateSummaryPath: string | null;
  promotedAt: string;
  gateResult: {
    passed: boolean;
    winRate: number;
    candidateWins: number;
    engineWins: number;
    tacticalWins: number;
    defaultAlphaWins: number;
    draws: number;
    aborted: number;
    timeouts: number;
    threshold: number;
    timeBudgetMs: number;
    maxSimulations: number;
    matchesPerOpponent: number;
  } | null;
}

// Auto-generated by \`pnpm alpha:promote\`. Do not edit by hand.
export const DEFAULT_ALPHA_MODEL_OVERRIDE: SerializedAlphaModel | null = ${JSON.stringify(serializedModel, null, 2)};

export const DEFAULT_ALPHA_MODEL_OVERRIDE_METADATA: DefaultAlphaModelOverrideMetadata | null = ${JSON.stringify(metadata, null, 2)};
`;
}

export function buildAlphaPromotionArchiveRecord({
  archiveDir,
  sourceModelId,
  sourceModelPath,
  archivedModelPath,
  gateSummaryPath,
  archivedGateSummaryPath,
  promotedAt,
  promotedModelId,
  gateResult,
}) {
  return {
    archiveDir,
    sourceModelId,
    sourceModelPath,
    archivedModelPath,
    gateSummaryPath,
    archivedGateSummaryPath,
    promotedAt,
    promotedModelId,
    gateResult,
  };
}
